### ISSUE TITLE
Breaks when sending the custom payload packet in a Bundle packet

### ISSUE THREAD

**Issue by bergerkiller** [56738/SmoothCoasters#10]
In TrainCarts it implements the SmoothCoastersAPI NetworkInterface to handle the packet sending in place of the default handler. With 1.19.4 my handler packs these packets inside Bundle packets, and for whatever reason this caused an occasional incompatibility.

https://github.com/bergerhealer/TrainCarts/blob/master/src/main/java/com/bergerkiller/bukkit/tc/controller/global/PacketQueue.java#L143

When some SmoothCoasters update packets are sent inside bundles and others are not, it seems sometimes the packets either don't arrive at the client or they arrive at the wrong order. I had a weird bug because of it that a player's first-person rotation did not reset after exiting from the seat. Likely because an in-flight update packet was received by the client after the reset, or that the reset rotation packets were all dropped.

I verified through intense debugging that this wasn't on my end, and the Bundle packet and the rotation reset packets were all sent to the player.

**Comment by 56738** [comment]
Fixed in https://github.com/56738/SmoothCoasters/commit/7092552c312c81fa06d0a4b8c5846f49cda6d471 and https://github.com/56738/SmoothCoastersAPI/commit/5dfc23df033c1d86278d9a48d416283b01ca7368.

Added protocol V5 to the mod (exactly the same as V4, it simply tells the server that no workaround is needed).
If the version is V4, the supplied NetworkInterface should not use bundle packets.
